#!/bin/bash



# This script is used to change the makefile to make the program depending on the os used.



# Check if the makefile exists
if [ $1 == "mac" ]; then
	mac=$(cat Makefile | grep "macos")
	if [ "$mac" == "#macos" ]; then
		echo "Makefile already set to mac ⛔"
		exit 1
	fi
	echo "Changing makefile to mac ✅"
	rm -rf linux
	mkdir -p linux
	mv Makefile linux
	mv includes/main.h linux
	cp macos/Makefile .
	cp macos/main.h includes/
elif [ $1 == "linux" ]; then
	linux=$(cat Makefile | grep "linux")
	if [ "$linux" == "#linux" ]; then
		echo "Makefile already set to linux ⛔"
		exit 1
	fi
	echo "Changing makefile to linux ✅"
	rm -rf macos
	mkdir -p macos
	mv Makefile macos
	mv includes/main.h macos
	cp linux/Makefile .
	cp linux/main.h includes/
else
	echo "Invalid os"
fi
